;;;;
;;;;   Light Color Theme 
;;;;
;;;;   Evgeniy N. Sharapov, 2010
;;;;
(eval-when-compile
  (require 'color-theme))
(defun sen-light-color-theme ()
  "Color theme by Evgeniy Sharapov, created 2010-09-03."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "White")
      (background-mode . light)
      (cursor-color . "DarkGrey")
      (foreground-color . "Black"))
     ((compilation-message-face . underline)
      (hl-line-face . hl-line)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "White" :foreground "Black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Monaco"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "dark blue"))))
     (compilation-column-number ((t (:foreground "VioletRed4"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Red1"))))
     (compilation-info ((t (:bold t :foreground "Green3" :weight bold))))
     (compilation-line-number ((t (:foreground "sienna"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "Monaco" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "Black" :background "White" :stipple nil :height 120))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (nil))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "magenta4"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "gray85"))))
     (custom-comment-tag ((t (:foreground "blue4"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "blue1"))))
     (custom-group-tag ((t (:bold t :family "Sans Serif" :foreground "blue1" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "red1" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "blue1"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "dark green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "blue1" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "blue1" :height 0.8))))
     (dimmed-paren ((t (:foreground "LightSlateGray"))))
     (dropdown-list-face ((t (:family "Monaco" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightyellow" :foreground "black" :height 120))))
     (dropdown-list-selection-face ((t (:stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "apple" :family "Monaco" :background "purple" :foreground "ivory" :height 120))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (ffap ((t (:background "darkseagreen2"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (font-lock-builtin-face ((t (:foreground "MediumOrchid4"))))
     (font-lock-comment-delimiter-face ((t (:italic t :slant italic :foreground "gray50"))))
     (font-lock-comment-face ((t (:italic t :foreground "gray50" :slant italic))))
     (font-lock-constant-face ((t (:foreground "dark cyan"))))
     (font-lock-doc-face ((t (:italic t :foreground "forestgreen" :background "gray90" :slant oblique))))
     (font-lock-function-name-face ((t (:foreground "blue"))))
     (font-lock-keyword-face ((t (:bold t :foreground "Purple" :weight semi-bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "MediumOrchid4"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "forestgreen"))))
     (font-lock-type-face ((t (:foreground "VioletRed4"))))
     (font-lock-variable-name-face ((t (:foreground "sienna"))))
     (font-lock-warning-face ((t (:bold t :foreground "Red1" :weight bold))))
     (fringe ((t (:background "grey95"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :family "Sans Serif" :weight bold :height 1.67))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t (:bold t :foreground "blue1" :weight bold))))
     (hi-green ((t (:background "green1"))))
     (hi-green-b ((t (:bold t :foreground "green1" :weight bold))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red1" :weight bold))))
     (hi-yellow ((t (:background "yellow1"))))
     (highlight ((t (:background "darkseagreen2"))))
     (hl-line ((t (:background "darkseagreen2"))))
     (hl-paren-face ((t (:bold t :weight bold))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "Red1"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "brown"))))
     (info-header-xref ((t (:foreground "blue1" :underline t))))
     (info-menu-header ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "brown" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
     (info-title-2 ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
     (info-title-3 ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
     (info-title-4 ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-xref ((t (:underline t :foreground "blue1"))))
     (info-xref-visited ((t (:foreground "magenta4" :underline t))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (linum ((t (:foreground "grey50"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (nil))))
     (message-cited-text ((t (:foreground "red"))))
     (message-header-cc ((t (:foreground "MidnightBlue"))))
     (message-header-name ((t (:foreground "cornflower blue"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "blue4" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "steel blue"))))
     (message-header-subject ((t (:bold t :foreground "navy blue" :weight bold))))
     (message-header-to ((t (:bold t :foreground "MidnightBlue" :weight bold))))
     (message-header-xheader ((t (:foreground "blue"))))
     (message-mml ((t (:foreground "ForestGreen"))))
     (message-separator ((t (:foreground "brown"))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (mouse ((t (nil))))
     (next-error ((t (:background "ns_selection_color"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (ns-working-text-face ((t (:underline t))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (region ((t (:background "ns_selection_color"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "yellow1"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "LimeGreen"))))
     (show-paren-mismatch ((t (:background "red" :foreground "white"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (yas/field-debug-face ((t (nil))))
     (yas/field-highlight-face ((t (:background "DarkSeaGreen1")))))))
(provide 'color-theme-sen-light)
