(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(color-theme-is-cumulative nil)
 '(column-number-mode t)
 '(custom-buffer-done-kill t)
 '(hl-paren-background-colors (quote ("tomato" "aquamarine3" "goldenrod" "magenta")))
 '(hl-paren-colors (quote ("black" "black" "black" "black")))
 '(inferior-lisp-program "clj")
 '(inhibit-startup-screen t)
 '(initial-scratch-message nil)
 '(muse-html-charset-default "utf-8")
 '(muse-html-encoding-default (quote utf-8))
 '(org-empty-line-terminates-plain-lists t)
 '(org-modules (quote (org-bbdb org-bibtex org-docview org-gnus org-id org-info org-jsinfo org-w3m org-panel)))
 '(recentf-max-saved-items 200)
 '(savehist-mode t nil (savehist))
 '(scalable-fonts-allowed t)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 10000)
 '(scroll-margin 5)
 '(scroll-preserve-screen-position t)
 '(scroll-step 1)
 '(show-paren-mode t)
 '(show-paren-style (quote mixed))
 '(swank-clojure-deps (list (concat "http://repo.technomancy.us/" "swank-clojure-1.1.0.jar") (concat "http://build.clojure.org/snapshots/org/" "clojure/clojure-contrib/1.2.0-SNAPSHOT/" "clojure-contrib-1.2.0-SNAPSHOT.jar") (concat "http://build.clojure.org/snapshots/org/" "clojure/clojure/1.2.0-master-SNAPSHOT/" "clojure-1.2.0-master-20100813.160144-94.jar")))
 '(use-dialog-box nil)
 '(visible-bell t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(completions-first-difference ((t (:inherit bold :underline t))))
 '(dropdown-list-selection-face ((t (:inherit dropdown-list-face :background "purple" :foreground "ivory"))))
 '(font-lock-comment-face ((((class color) (min-colors 88) (background light)) (:foreground "gray50" :slant italic))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face :background "gray90" :slant oblique))))
 '(font-lock-function-name-face ((((class color) (min-colors 88) (background light)) (:foreground "blue"))))
 '(font-lock-keyword-face ((((class color) (min-colors 88) (background light)) (:foreground "Purple" :weight semi-bold))))
 '(font-lock-string-face ((((class color) (min-colors 88) (background light)) (:foreground "forestgreen"))))
 '(font-lock-type-face ((((class color) (min-colors 88) (background light)) (:foreground "VioletRed4"))))
 '(hi-green-b ((((min-colors 88)) (:foreground "green4" :weight bold))))
 '(hl-paren-face ((t (:weight bold))) t)
 '(org-level-1 ((t (:foreground "blue"))))
 '(org-level-2 ((t (:foreground "turquoise4"))))
 '(org-level-3 ((t (:foreground "green4"))))
 '(org-level-4 ((t (:foreground "goldenrod"))))
 '(org-level-5 ((t (:foreground "chocolate"))))
 '(org-level-6 ((t (:foreground "violetred"))))
 '(org-level-7 ((t (:foreground "purple"))))
 '(org-link ((((class color) (background light)) (:foreground "deepskyblue3" :underline t))))
 '(sh-quoted-exec ((((class color) (background light)) (:background "gray85"))))
 '(show-paren-match ((((class color) (background light)) (:background "LimeGreen"))))
 '(show-paren-mismatch ((((class color)) (:background "red" :foreground "white")))))
