(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(bmkp-last-as-first-bookmark-file "~/.emacs.d/bookmarks")
 '(byte-compile-verbose nil)
 '(color-theme-is-cumulative t)
 '(column-number-mode t)
 '(compilation-scroll-output (quote first-error))
 '(custom-buffer-done-kill t)
 '(custom-safe-themes (quote ("7fe1e3de3e04afc43f9a3d3a8d38cd0a0efd9d4c" "d14db41612953d22506af16ef7a23c4d112150e5" default)))
 '(delete-old-versions t)
 '(delete-selection-mode t)
 '(desktop-globals-to-save (quote (desktop-missing-file-warning tags-file-name tags-table-list search-ring regexp-search-ring regexp-history register-alist file-name-history extended-command-history grep-history ido-last-directory-list minibuffer-history query-replace-history shell-command-history)))
 '(desktop-save-mode t)
 '(echo-keystrokes 0.1)
 '(font-lock-verbose nil)
 '(global-auto-revert-mode t)
 '(hippie-expand-try-functions-list (quote (try-expand-dabbrev try-expand-dabbrev-all-buffers try-expand-dabbrev-from-kill try-expand-all-abbrevs try-complete-file-name-partially try-complete-file-name try-expand-list try-expand-line)))
 '(history-delete-duplicates t)
 '(history-length t)
 '(hl-paren-background-colors (quote ("tomato" "aquamarine3" "goldenrod" "magenta")))
 '(hl-paren-colors (quote ("black" "black" "black" "black")))
 '(ido-auto-merge-work-directories-length -1)
 '(ido-create-new-buffer (quote always))
 '(ido-enable-flex-matching t)
 '(ido-max-prospects 10)
 '(ido-show-dot-for-dired t)
 '(ido-use-filename-at-point (quote guess))
 '(ido-use-virtual-buffers t)
 '(indent-tabs-mode nil)
 '(indicate-empty-lines t)
 '(inhibit-startup-screen t)
 '(initial-scratch-message nil)
 '(kept-new-versions 3)
 '(mouse-avoidance-mode (quote animate) nil (avoid))
 '(mouse-yank-at-point t)
 '(muse-html-charset-default "utf-8")
 '(muse-html-encoding-default (quote utf-8))
 '(org-agenda-include-diary t)
 '(org-clock-clocktable-default-properties (quote (:maxlevel 4 :scope file :step week :block thisweek :tend "")))
 '(org-completion-use-ido t)
 '(org-empty-line-terminates-plain-lists t)
 '(org-hide-leading-stars t)
 '(org-modules (quote (org-bbdb org-bibtex org-docview org-gnus org-id org-info org-jsinfo org-special-blocks org-w3m org-panel)))
 '(org-return-follows-link t)
 '(org-use-sub-superscripts (quote {}))
 '(recentf-max-saved-items 1000)
 '(recentf-mode t)
 '(require-final-newline t)
 '(rspec-use-rvm t)
 '(save-place t nil (saveplace))
 '(savehist-mode t nil (savehist))
 '(scalable-fonts-allowed t)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 10000)
 '(scroll-margin 5)
 '(scroll-preserve-screen-position t)
 '(scroll-step 1)
 '(sentence-end-double-space nil)
 '(shift-select-mode nil)
 '(show-paren-mode t)
 '(show-paren-style (quote mixed))
 '(show-trailing-whitespace t)
 '(tab-always-indent (quote complete))
 '(undo-limit 2000000)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(use-dialog-box nil)
 '(user-full-name "Evgeniy Sharapov")
 '(user-mail-address "evgeniy.sharapov@gmail.com")
 '(visible-bell t)
 '(winner-mode t nil (winner)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(diff-added ((t (:inherit diff-changed :foreground "DarkGreen"))))
 '(diff-removed ((t (:inherit diff-changed :foreground "firebrick2"))))
 '(font-lock-comment-face ((t (:foreground "Firebrick" :slant oblique))))
 '(org-level-4 ((t (:inherit outline-4 :slant normal))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "dim gray"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "SkyBlue3"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "aquamarine4"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "khaki4"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "IndianRed2"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "burlywood4"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "chocolate2"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "orange3"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "HotPink3"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "DarkRed"))))
 '(trailing-whitespace ((t (:background "IndianRed1")))))
