;;
;; Feast For Eyes ( dark ) theme 
;;
;; Evgeniy Sharapov, 2010
;; 
;; http://www.feastforeyes.com  
;;
(eval-when-compile    
	(require 'color-theme))

;; Let's define basic palette
(defvar feastforeyes-bg "")
(defvar feastforeyes-fg "")


(defun color-theme-feast-for-eyes ()
  "Feast For Eyes ( dark ) theme  for Emacs color-theme created 2010-09-08 by Evgeniy Sharapov."
  (interactive)
  (color-theme-install
   '(color-theme-feast-for-eyes

     ((background-color . "#111")
      (background-mode . dark)
      (border-color . "#111")
      (cursor-color . "yellow")
      (foreground-color . "#ddd")
      (mouse-color . "sienna1"))

     ((compilation-message-face . underline)
      (hl-line-face . hl-line)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (org-goto-interface . outline)
      (widget-mouse-face . highlight))

     (default ((t (:stipple nil :background "#111" :foreground "#ddd" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "Consolas"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "#111"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (nil))))
     (buffers-tab ((t (:background "#111" :foreground "#ddd"))))
     (button ((t (nil))))
     (comint-highlight-input ((t (nil))))
     (comint-highlight-prompt ((t (nil))))
     (compilation-column-number ((t (nil))))
     (compilation-error ((t (nil))))
     (compilation-info ((t (nil))))
     (compilation-line-number ((t (nil))))
     (compilation-warning ((t (nil))))
     (completions-annotations ((t (nil))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (nil))))
     (cursor ((t (:background "yellow"))))
     (custom-button ((t (nil))))
     (custom-button-mouse ((t (nil))))
     (custom-button-pressed ((t (nil))))
     (custom-button-pressed-unraised ((t (nil))))
     (custom-button-unraised ((t (nil))))
     (custom-changed ((t (nil))))
     (custom-comment ((t (nil))))
     (custom-comment-tag ((t (nil))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (nil))))
     (custom-group-tag ((t (nil))))
     (custom-group-tag-1 ((t (nil))))
     (custom-invalid ((t (nil))))
     (custom-link ((t (nil))))
     (custom-modified ((t (nil))))
     (custom-rogue ((t (nil))))
     (custom-saved ((t (nil))))
     (custom-set ((t (nil))))
     (custom-state ((t (nil))))
     (custom-themed ((t (nil))))
     (custom-variable-button ((t (nil))))
     (custom-variable-tag ((t (nil))))
     (custom-visibility ((t (nil))))
     (dimmed-paren ((t (nil))))
     (dropdown-list-face ((t (nil))))
     (dropdown-list-selection-face ((t (nil))))
     (eldoc-highlight-function-argument ((t (nil))))
     (epa-field-body ((t (nil))))
     (epa-field-name ((t (nil))))
     (epa-mark ((t (nil))))
     (epa-string ((t (nil))))
     (epa-validity-disabled ((t (nil))))
     (epa-validity-high ((t (nil))))
     (epa-validity-low ((t (nil))))
     (epa-validity-medium ((t (nil))))
     (erc-current-nick-face ((t (:foreground "#aeaeae"))))
     (erc-default-face ((t (:foreground "#ddd"))))
     (erc-keyword-face ((t (:foreground "#cf6a4c"))))
     (erc-notice-face ((t (:foreground "#666"))))
     (erc-timestamp-face ((t (:foreground "#65b042"))))
     (erc-underline-face ((t (:foreground "c5af75"))))
     (escape-glyph ((t (nil))))
     (ffap ((t (nil))))
     (file-name-shadow ((t (nil))))
     (fixed-pitch ((t (:family "Monospace"))))
     (font-lock-builtin-face ((t (:foreground "#dd7b3b"))))
     (font-lock-comment-delimiter-face ((t (nil))))
     (font-lock-comment-face ((t (:foreground "#666"))))
     (font-lock-constant-face ((t (:foreground "#99cf50"))))
     (font-lock-doc-face ((t (nil))))
     (font-lock-doc-string-face ((t (:foreground "#9b859d"))))
     (font-lock-function-name-face ((t (:bold t :foreground "#e9c062" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "#cf6a4c" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "#aeaeae"))))
     (font-lock-reference-face ((t (:foreground "8b98ab"))))
     (font-lock-regexp-grouping-backslash ((t (nil))))
     (font-lock-regexp-grouping-construct ((t (nil))))
     (font-lock-string-face ((t (:foreground "#65b042"))))
     (font-lock-type-face ((t (:foreground "#c5af75"))))
     (font-lock-variable-name-face ((t (:foreground "#3387cc"))))
     (font-lock-warning-face ((t (:bold t :background "#420e09" :foreground "#eeeeee" :weight bold))))
     (fringe ((t (nil))))
     (gui-element ((t (:background "#0e2231" :foreground "black"))))
     (header-line ((t (nil))))
     (help-argument-name ((t (nil))))
     (hi-black-b ((t (nil))))
     (hi-black-hb ((t (nil))))
     (hi-blue ((t (nil))))
     (hi-blue-b ((t (nil))))
     (hi-green ((t (nil))))
     (hi-green-b ((t (nil))))
     (hi-pink ((t (nil))))
     (hi-red-b ((t (nil))))
     (hi-yellow ((t (nil))))
     (highlight ((t (:italic t :bold t :slant italic :weight bold))))
     (highline-face ((t (:background "#4a410d"))))
     (hl-line ((t (nil))))
     (hl-paren-face ((t (nil))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (nil))))
     (ido-indicator ((t (nil))))
     (ido-only-match ((t (nil))))
     (ido-subdir ((t (nil))))
     (info-header-node ((t (nil))))
     (info-header-xref ((t (nil))))
     (info-menu-header ((t (nil))))
     (info-menu-star ((t (nil))))
     (info-node ((t (nil))))
     (info-title-1 ((t (nil))))
     (info-title-2 ((t (nil))))
     (info-title-3 ((t (nil))))
     (info-title-4 ((t (nil))))
     (info-xref ((t (nil))))
     (info-xref-visited ((t (nil))))
     (isearch ((t (nil))))
     (isearch-fail ((t (nil))))
     (italic ((t (nil))))
     (lazy-highlight ((t (nil))))
     (left-margin ((t (nil))))
     (link ((t (nil))))
     (link-visited ((t (nil))))
     (linum ((t (nil))))
     (match ((t (nil))))
     (menu ((t (nil))))
     (message-cited-text ((t (nil))))
     (message-header-cc ((t (nil))))
     (message-header-name ((t (nil))))
     (message-header-newsgroups ((t (nil))))
     (message-header-other ((t (nil))))
     (message-header-subject ((t (nil))))
     (message-header-to ((t (nil))))
     (message-header-xheader ((t (nil))))
     (message-mml ((t (nil))))
     (message-separator ((t (nil))))
     (minibuffer-noticeable-prompt ((t (nil))))
     (minibuffer-prompt ((t (nil))))
     (mmm-default-submode-face ((t (:background "#111"))))
     (mode-line ((t (:background "#e6e5e4" :foreground "black"))))
     (mode-line-buffer-id ((t (nil))))
     (mode-line-emphasis ((t (nil))))
     (mode-line-highlight ((t (nil))))
     (mode-line-inactive ((t (nil))))
     (mouse ((t (nil))))
     (next-error ((t (nil))))
     (nobreak-space ((t (nil))))
     (nxml-attribute-colon-face ((t (:foreground "#e28964"))))
     (nxml-attribute-local-name-face ((t (:foreground "#3387cc"))))
     (nxml-attribute-prefix-face ((t (:foreground "#cf6a4c"))))
     (nxml-attribute-value-delimiter-face ((t (:foreground "#99cf50"))))
     (nxml-attribute-value-face ((t (:foreground "#65b042"))))
     (nxml-comment-content-face ((t (:foreground "#666"))))
     (nxml-comment-delimiter-face ((t (:foreground "#333"))))
     (nxml-element-local-name-face ((t (:foreground "#e9c062"))))
     (nxml-markup-declaration-delimiter-face ((t (:foreground "#aeaeae"))))
     (nxml-namespace-attribute-prefix-face ((t (:foreground "#9b859d"))))
     (nxml-namespace-attribute-xmlns-face ((t (:foreground "#8b98ab"))))
     (nxml-prolog-keyword-face ((t (:foreground "#c5af75"))))
     (nxml-prolog-literal-content-face ((t (:foreground "#dad085"))))
     (nxml-tag-delimiter-face ((t (:foreground "#cda869"))))
     (nxml-tag-slash-face ((t (:foreground "#cda869"))))
     (nxml-text-face ((t (:foreground "#ddd"))))
     (org-agenda-clocking ((t (nil))))
     (org-agenda-column-dateline ((t (nil))))
     (org-agenda-date ((t (nil))))
     (org-agenda-date-today ((t (nil))))
     (org-agenda-date-weekend ((t (nil))))
     (org-agenda-dimmed-todo-face ((t (nil))))
     (org-agenda-done ((t (nil))))
     (org-agenda-restriction-lock ((t (nil))))
     (org-agenda-structure ((t (nil))))
     (org-archived ((t (nil))))
     (org-block ((t (nil))))
     (org-checkbox ((t (nil))))
     (org-checkbox-statistics-done ((t (nil))))
     (org-checkbox-statistics-todo ((t (nil))))
     (org-clock-overlay ((t (nil))))
     (org-code ((t (nil))))
     (org-column ((t (:family "Consolas"))))
     (org-column-title ((t (nil))))
     (org-date ((t (nil))))
     (org-done ((t (nil))))
     (org-drawer ((t (nil))))
     (org-ellipsis ((t (nil))))
     (org-footnote ((t (nil))))
     (org-formula ((t (nil))))
     (org-headline-done ((t (nil))))
     (org-hide ((t (nil))))
     (org-latex-and-export-specials ((t (nil))))
     (org-level-1 ((t (nil))))
     (org-level-2 ((t (nil))))
     (org-level-3 ((t (nil))))
     (org-level-4 ((t (nil))))
     (org-level-5 ((t (nil))))
     (org-level-6 ((t (nil))))
     (org-level-7 ((t (nil))))
     (org-level-8 ((t (nil))))
     (org-link ((t (nil))))
     (org-meta-line ((t (nil))))
     (org-mode-line-clock ((t (nil))))
     (org-property-value ((t (nil))))
     (org-scheduled ((t (nil))))
     (org-scheduled-previously ((t (nil))))
     (org-scheduled-today ((t (nil))))
     (org-sexp-date ((t (nil))))
     (org-special-keyword ((t (nil))))
     (org-table ((t (nil))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (nil))))
     (org-time-grid ((t (nil))))
     (org-todo ((t (nil))))
     (org-upcoming-deadline ((t (nil))))
     (org-verbatim ((t (nil))))
     (org-warning ((t (nil))))
     (outline-1 ((t (nil))))
     (outline-2 ((t (nil))))
     (outline-3 ((t (nil))))
     (outline-4 ((t (nil))))
     (outline-5 ((t (nil))))
     (outline-6 ((t (nil))))
     (outline-7 ((t (nil))))
     (outline-8 ((t (nil))))
     (primary-selection ((t (:background "#222"))))
     (query-replace ((t (nil))))
     (region ((t (:background "#4a410d"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (nil))))
     (sh-special-variables-face ((t (nil))))
     (shadow ((t (nil))))
     (show-paren-match ((t (nil))))
     (show-paren-mismatch ((t (nil))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (tmm-inactive ((t (nil))))
     (tool-bar ((t (nil))))
     (tooltip ((t (nil))))
     (trailing-whitespace ((t (nil))))
     (underline ((t (:underline nil))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (nil))))
     (widget-button-pressed ((t (nil))))
     (widget-documentation ((t (nil))))
     (widget-field ((t (nil))))
     (widget-inactive ((t (nil))))
     (widget-single-line-field ((t (nil))))
     (yas/field-debug-face ((t (nil))))
     (yas/field-highlight-face ((t (nil)))))))

(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))
